version: '3.7'
services:
  nginx:
    container_name: textransfer_nginx
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - .:/var/www/html/app
      - ./docker/nginx:/etc/nginx/conf.d/
    links:
      - php
    networks:
      default:
        aliases:
          - local-api.textransfer.tech
      textransfer:
        aliases:
          - local-api-service.textransfer.tech
  php:
    container_name: textransfer_php
    build: docker/php
    volumes:
      - .:/var/www/html/app
  mysql:
    container_name: textransfer_mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - local-database.textransfer.tech
      textransfer:
        aliases:
          - local-database.textransfer.tech
networks:
  default:
    ipam:
      config:
        - subnet: 11.0.3.0/24
  textransfer:
    external: true